general:
  data_base_dir: /app/data
  version: 1.0.0
  description: DeepSpA model for incorporating anatomical awareness in the prediction of radiographic sacroiliitis

execute:
  - DicomImporter
  - DeepSpARunner
  - ReportExporter
  - DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: True
    meta: 
      mod: '%Modality'

  ReportExporter:
    includes:
    - static:
      label: Model
      value: DeepSpA Classifier
    - data: raxSpAprob
      label: r-axSpA Probability
      value: value
    - data: raxSpAprob
      label: r-axSpA Probability Description
      value: description
    - data: nraxSpAprob
      label: no r-axSpA Probability
      value: value
    - data: nraxSpAprob
      label: no r-axSpA Probability Description
      value: description
    - data: binarized_pred
      label: Binarized Prediction
      value: value
    - data: binarized_pred
      label: Binarized Prediction Description
      value: description

  DataOrganizer:
    targets:
      - png:mod=seg-->[i:sid]/[basename]
      - png:mod=box-->[i:sid]/[basename]
      - png:mod=gradcam-->[i:sid]/[basename]
      - json-->[i:sid]/deepspa_predictions.json
